In [1]:
import pandas as pd 
import os

# Your original data_path without a slash
data_path = '../data'
file_name_1 = 'Flight Level Data.csv'
file_name_2 = 'PNR+Flight+Level+Data.csv'
file_name_3 = 'PNR Remark Level Data.csv'
file_name_4 = 'Bag+Level+Data.csv'
file_name_5 = 'Airports Data.csv'

# Safely join the path components
full_path_1 = os.path.join(data_path, file_name_1)
full_path_2 = os.path.join(data_path, file_name_2)
full_path_3 = os.path.join(data_path, file_name_3)
full_path_4 = os.path.join(data_path, file_name_4)
full_path_5 = os.path.join(data_path, file_name_5)
# Read the CSV
flight_df = pd.read_csv(full_path_1)
pnr_flight_df= pd.read_csv(full_path_2)
pnr_remark_df= pd.read_csv(full_path_3)
bag_df= pd.read_csv(full_path_4)
airport_df= pd.read_csv(full_path_5)
print("File loaded successfully!")

File loaded successfully!

In [2]:
flight_df.head()

,company_id,flight_number,scheduled_departure_date_local,scheduled_departure_station_code,scheduled_arrival_station_code,scheduled_departure_datetime_local,scheduled_arrival_datetime_local,actual_departure_datetime_local,actual_arrival_datetime_local,total_seats,fleet_type,carrier,scheduled_ground_time_minutes,actual_ground_time_minutes,minimum_turn_minutes
0,OO,4792,2025-08-04,ORD,ROA,2025-08-04T17:57:00Z,2025-08-04T21:04:00Z,2025-08-04T18:04:00Z,2025-08-04T20:52:00Z,76,ERJ-175,Express,42,34,34
1,UA,920,2025-08-03,ORD,LHR,2025-08-03T18:05:00Z,2025-08-04T08:20:00Z,2025-08-03T18:27:00Z,2025-08-04T08:06:00Z,167,B767-300,Mainline,235,229,145
2,UA,1776,2025-08-10,ORD,PHL,2025-08-10T18:20:00Z,2025-08-10T21:35:00Z,2025-08-10T20:11:00Z,2025-08-10T23:26:00Z,166,B737-800,Mainline,76,69,51
3,OO,5790,2025-08-06,ORD,CRW,2025-08-06T18:20:00Z,2025-08-06T21:04:00Z,2025-08-06T20:05:00Z,2025-08-06T22:42:00Z,50,CRJ-200,Express,223,38,29
4,UA,1398,2025-08-05,ORD,ATL,2025-08-05T18:20:00Z,2025-08-05T21:29:00Z,2025-08-05T18:16:00Z,2025-08-05T21:49:00Z,166,B737-800,Mainline,75,72,51